name: golint
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version-file: ./go.mod
      - uses: golangci/golangci-lint-action@9d1e0624a798bb64f6c3cea93db47765312263dc
