name: Publish to pkg.go.dev

on:
  push:
    tags:
      - v0.**

permissions:
  contents: read

jobs:
  publish_on_pkg_go_dev:
    name: publish a new version in pkg.go.dev
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version-file: ./go.mod

      - name: Publish on pkg.go.dev
        run: GOPROXY=proxy.golang.org go list -m github.com/np-guard/models@${{ github.ref_name }}
